import { registerModule } from '../../../core/permissions/registry';
import { UserRole, PERMISSIONS } from '../../../types';

export function registerHRPermissions(): void {
  registerModule({
    module: 'hr',
    permissions: [
      PERMISSIONS.EMPLOYEE_CREATE,
      PERMISSIONS.EMPLOYEE_READ,
      PERMISSIONS.EMPLOYEE_UPDATE,
      PERMISSIONS.EMPLOYEE_DELETE,
      PERMISSIONS.SITE_CREATE,
      PERMISSIONS.SITE_READ,
      PERMISSIONS.SITE_UPDATE,
      PERMISSIONS.COMPANY_CREATE,
      PERMISSIONS.COMPANY_READ,
      PERMISSIONS.COMPANY_UPDATE,
      PERMISSIONS.GUARD_REGISTER,
      PERMISSIONS.GUARD_ASSIGN_SITE,
      PERMISSIONS.GUARD_MODIFY_HOURS,
      PERMISSIONS.GUARD_ATTENDANCE_READ,
      PERMISSIONS.GUARD_ATTENDANCE_MANAGE,
      PERMISSIONS.GUARD_ATTENDANCE_FUTURE,
      PERMISSIONS.GUARD_ATTENDANCE_SELF,
      PERMISSIONS.STAFF_ATTENDANCE_MANAGE,
      PERMISSIONS.ORGANIZATION_READ,
      PERMISSIONS.ORGANIZATION_MANAGE,

    ],
    roleDefaults: {
      [UserRole.HR_ADMIN]: [
        PERMISSIONS.EMPLOYEE_CREATE,
        PERMISSIONS.EMPLOYEE_READ,
        PERMISSIONS.EMPLOYEE_UPDATE,
        PERMISSIONS.SITE_CREATE,
        PERMISSIONS.SITE_READ,
        PERMISSIONS.SITE_UPDATE,
        PERMISSIONS.COMPANY_CREATE,
        PERMISSIONS.COMPANY_READ,
        PERMISSIONS.COMPANY_UPDATE,
        PERMISSIONS.GUARD_REGISTER,
        PERMISSIONS.GUARD_ASSIGN_SITE,
        PERMISSIONS.GUARD_ATTENDANCE_READ,
        PERMISSIONS.GUARD_ATTENDANCE_MANAGE,
        PERMISSIONS.GUARD_ATTENDANCE_FUTURE,
        PERMISSIONS.STAFF_ATTENDANCE_MANAGE,
        PERMISSIONS.ORGANIZATION_READ,
        PERMISSIONS.ORGANIZATION_MANAGE,

      ],
      [UserRole.OPERATIONS]: [
        PERMISSIONS.EMPLOYEE_READ,
        PERMISSIONS.SITE_READ,
        PERMISSIONS.COMPANY_READ,
        PERMISSIONS.GUARD_ASSIGN_SITE,
        PERMISSIONS.GUARD_MODIFY_HOURS,
        PERMISSIONS.GUARD_ATTENDANCE_READ,
        PERMISSIONS.GUARD_ATTENDANCE_MANAGE,
      ],
      [UserRole.GUARD]: [
        PERMISSIONS.EMPLOYEE_READ,
        PERMISSIONS.SITE_READ,
        PERMISSIONS.GUARD_ATTENDANCE_SELF,
      ],
    },
  });
}
